### ISSUE TITLE
[Suggestion] Thaumcraft Page Displaying Recipes

### ISSUE THREAD

**Issue by xilleto** [MineTweaker/ModTweaker#142]
Add a feature to specify which research should the recipe display instead of randomly searching for a random recipe to display.

**Comment by Yulife** [comment]
What do you mean by that? :) I'm kinda confused, lol.

**Comment by Zixxl** [comment]
Let's say you have two different recipes for creating Nitor in a crucible. You want to add both recipes to the Thaumonomicon so players can look up the recipes. However the handler for adding new pages to the Thaumonomicon only looks for the output (Nitor) and picks the first recipes which matches and ignores others.

**Comment by Yulife** [comment]
Ahhhh! Now I get it. Awesome.

**Comment by Voidi** [comment]
Problem: How to specify a particular recipe, The recipes are in an unordered list, without a extra key/index

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.
