### ISSUE TITLE
[Suggestion] Hidden Research and Mystical Construct Support

### ISSUE THREAD

**Issue by Dream-Master** [MineTweaker/ModTweaker#203]
Every time you clear a page you can re add only Text Pages, crucible pages, infusion pages and Arcane Workbench Pages. Is there a way to re add magical Construct (Multiblock Structures) and smelting recipes? Otherwise the Sites ar empty.
If it is all ready in the code can someone say me how it works ?
Thanks in advance.

**Comment by Yulife** [comment]
https://github.com/Azanor/thaumcraft-api/blob/master/research/ResearchPage.java#L29

Smelting should be doable.

Didn't found anything regarding a multiblock, maybe it's Compound Crafting?

**Comment by Dream-Master** [comment]
I think Compound Crafting can be the multiblock stuctures.

**Comment by Voidi** [comment]
Get it working? Can the issue be closed?

**Comment by Dream-Master** [comment]
I think it isn't added yet.

**Comment by Voidi** [comment]
Could you give me a existing example for both recipe types?

**Comment by Dream-Master** [comment]
Hidden Research like The Bone Bow. Scanning different items to get this unlocked.

The Multi Block is only a visual thing 
It would be nice to give us a add Page Multistructural code (like add Infusion Page ore add Arcane Page) where we can add as example the Infusion Table recipes (how to place the Blocks there)
I need it because if i delete Pages in the Bock i cant re add their Structures. (Infusion Table or the Thaumcraft Multiblock Furnace)
I hope you understand me or better in german ?

**Comment by Voidi** [comment]
ich brauch ein Beispiel für ein 'Rezept' diese Typs Compound habe ich ein paar gefunden (nur weiß ich da noch nicht genau, wie das programmmiert wird)
Kannst du mir konkrete Beispiel für Smelting geben, oder sind das normale Furnace Rezepte?

**Comment by Yulife** [comment]
The multiblock thing is more of an IE multi block page than hitting something-with-a-wand-page. i doubt it's possible.

**Comment by Dream-Master** [comment]
@ ich mache screenshots später.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/11377912/c63c4a96-92e8-11e5-9902-862c9ccc730b.png)

![image](https://cloud.githubusercontent.com/assets/2970688/11377935/df42c6b4-92e8-11e5-8ac4-ed9352c63d84.png)

![image](https://cloud.githubusercontent.com/assets/2970688/11377954/ffd3754a-92e8-11e5-9600-179d0ff44a11.png)

@Voidi 
Adding a addPage command would be enough to change or re-add those recipes/pages too.

If changing recipes are not possible than to readd those Pages when remove a Page or a whole Tab.

**Comment by Dream-Master** [comment]
@Voidi  The Info about the hidden research you need too ?

**Comment by Voidi** [comment]
If you me -explain how hidden research actually should work- then yes.

**Comment by Dream-Master** [comment]
i look into Thaumcraft api maybe i can find it.

**Comment by Dream-Master** [comment]
Hidden research woks like this.

Bone Bow

Scan a Bow and scan a Bone and you get the hidden research.

**Comment by Dream-Master** [comment]
Not sure if this is the magical construct

https://github.com/Azanor/thaumcraft-api/blob/4120e665c9c3d88324baa3676283d7fb8ba25f1c/research/ResearchPage.java#L104

**Comment by Dream-Master** [comment]
This is not a coding Page but maybe explain what i need for the Book.

http://minecraft.gamepedia.com/Template:Inventory_slot/Thaumcraft/Mystical_Construct

**Comment by Yulife** [comment]
Didn't I explain the hidden knowledge to you @Voidi ?

**Comment by Dream-Master** [comment]
Have 3 triggers, item, entity or aspect.

**Comment by jaredlll08** [comment]
Ok this has got to be the most anoyying issue so far , so lets be logcal
here, please explain what you want added, the. Explain that as if you were
going to explain it to a 5 year old. That way, we can see exactly why you
want, because this issue has gone from pages to hidden scanning etc.

**Comment by Dream-Master** [comment]
OK i am now 5 Years old....
I want you add:
1. Hidden research support with all triggers (item, entity and aspect.)
2. Adding Page support for the mystical construct (this is only i visual thing i think, see Photos above)

THANK YOU

**Comment by jaredlll08** [comment]
@yulife, do we not already have hidden research support?

**Comment by Dream-Master** [comment]
It not working atm.

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.
