### ISSUE TITLE
Ex Nihilo Sieve Recipes in Ex Astris

### ISSUE THREAD

**Issue by Sir-Will** [MineTweaker/ModTweaker#211]
hey,
with version
- ModTweaker-2-0.9.1
- Ex-Astris-MC1.7.10-1.16-36
- Ex-Nihilo-1.38-44

Custom Ex Nihilo recipes no longer work with Ex Astris.

For example adding this recipe:
``mods.exnihilo.Sieve.addRecipe(<GalacticraftCore:tile.moonBlock:3>, <minecraft:blaze_rod>, 80);``
It is possible to sieve it with Ex Nihilo sieves but not with the auto sieve from Ex Astris

**Comment by Zixxl** [comment]
I changed the way the handlers apply the recipes in the New ModTweaker versions. I'll check if we can fix this.

**Comment by SirWilli** [comment]
That would be great, thanks.

**Comment by Zixxl** [comment]
I'll guess it is because Ex-Astris caches which items are allowed or not allowed to be sieved. Have you tried reloading minecraft or did you change the recipe in-game via ```/mt reload```?

**Comment by SirWilli** [comment]
I didn't change the recipes and also didn't reload it.

**Comment by SirWilli** [comment]
@Zixxl any news to this?

**Comment by jaredlll08** [comment]
Ex nihilo caches their recipes, nothing we can do about it.

**Comment by SirWilli** [comment]
What do you mean?

**Comment by jaredlll08** [comment]
Sorry, I meant that ex astris caches them, basicly, when the game loads,
they copy the list that has all the recipes, but we only edit the list
later.

**Comment by SirWilli** [comment]
Okay, created an issue there: https://github.com/Ex-Astris-Rebirth/Ex-Astris-Rebirth/issues/59

**Comment by almightyfoon** [comment]
Are there any work arrounds for this or is this just something we need to wait for the Ex Astris dev to fix?

**Comment by jaredlll08** [comment]
Wait for Ex nihilo dev to fix.

**Comment by MikeLydeamore** [comment]
Ex Astris does not cache sieve recipes, and has not done for a while. They are pulled directly from SieveRegistry.siftables in Ex Nihilo.

**Comment by joye-ramone** [comment]
Looks like that this feature get broken between ModTweaker-2-0.8.3 and ModTweaker-2-0.9.0.
Version ModTweaker-2-0.8.3 still works well with all other plugins.

Probably this can be fixed or workaround on ModTweaker side? This is so annoying that you cannot use this plugins together.

**Comment by joye-ramone** [comment]
Btw, Hammer recipes working good in AutoHammer from Ex Astrisю
Also I have tested other version of Ex Astris: Ex-Astris-Rebirth https://github.com/Ex-Astris-Rebirth/Ex-Astris-Rebirth and it has exactly the same issue.

**Comment by KaneHart** [comment]
Also having this issue with 
Ex-Astris-MC1.7.10-1.16-36
MineTweaker3-1.7.10-3.0.10B
ModTweaker2-0.9.5

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.
