### ISSUE TITLE
[Questions] Hidden Thaumcraft Research

### ISSUE THREAD

**Issue by Dream-Master** [MineTweaker/ModTweaker#212]
Is it possible to add hidden Research like the Thaumcraft Bone Bow do with Modtweaker?
(Need to scanning a Bow, Bone and a String)
If it is inside already can someone explain me how it works.
Thanks in advance.

**Comment by Dream-Master** [comment]
I found something in the Api from Thaumcraft but not sure if it is implemented.
https://github.com/Azanor/thaumcraft-api/blob/master/research/ResearchItem.java#L119
https://github.com/Azanor/thaumcraft-api/blob/master/research/ResearchItem.java#L124
https://github.com/Azanor/thaumcraft-api/blob/master/research/ResearchItem.java#L129

**Comment by Yulife** [comment]
This was done in a different Modtweaker2 version, however, it was never retrieved into this version. I'll look into it tomorrow, maybe :)

**Comment by Yulife** [comment]
https://github.com/jaredlll08/ModTweaker2/commit/6fd85cbd10959e45e28199a07e125e2d15a0068d

**Comment by jaredlll08** [comment]
http://ci.tterrag.com/job/ModTweaker2/107/

**Comment by Yulife** [comment]
I just brought the code back - you need to fix it! ;)

**Comment by jaredlll08** [comment]
That is not how this works.

**Comment by Yulife** [comment]
Well, you ignored my request to bring it back so here you go!

**Comment by jaredlll08** [comment]
no, you do something, you make sure it is done right.

**Comment by Dream-Master** [comment]
Cool will try it later

**Comment by jaredlll08** [comment]
Well you can't, that build failed. And I got school work to do.

**Comment by Dream-Master** [comment]
So but it is possible to add this in the future?

**Comment by Yulife** [comment]
Could you look into it Dream-Master? I would but I'm really busy irl.

**Comment by Dream-Master** [comment]
I can but i don't know if I can fix it.

**Comment by Dream-Master** [comment]
Any news here how it works?

**Comment by Voidi** [comment]
Any news if this work?

**Comment by Dream-Master** [comment]
Not sure. I not find an example file in the Wiki. I try it only looking in the source and make a recipe but this not working or i am failed (not give any error back to the syntax is must be right)

**Comment by Voidi** [comment]
@Yulife can you explain how this should used?

**Comment by Yulife** [comment]
There are triggers in Thaumcraft that lead to the ability to unlock a research. You can do it with 1: Aspects 2: Items and 3: Entities. Once you scan either the research is ready to be unlocked. An example is scanning a bone which unlocks the Bone Bow.

**Comment by Dream-Master** [comment]
Thats what we know already. I mean if we add a new thing that have hidden research like a bone bow. Maybe scanning glass and a tank give some thaumcraft tank/jar

**Comment by Voidi** [comment]
A note: Hidden Research don't work a the Moment

**Comment by Dream-Master** [comment]
Will it be in the future ?

And adding Magical Construct to Modtweaker would help to edit every site in Thaumcraft. (Multi Block Stucture Recipes )

**Comment by Voidi** [comment]
you mean this #203 ?
I don't know, everyone is welcome to contribute or convince the Mod Author to support Minetweaker themselve.
Maybe i find some motivation, to do it.

**Comment by Dream-Master** [comment]
Yes this one. If my Java knowledge is better i do it by my self but i can't. Sorry.

**Comment by Dream-Master** [comment]
Any news here ? I could need this future now.

**Comment by jaredlll08** [comment]
Well here we have a problem,  if I work on mod tweaker,  it will be porting to 1.8, in which case I will look into having this,  so basically,  don't expect this for 1.7, from me at least

**Comment by Dream-Master** [comment]
My pack is for MC 1.7.10. I cant update my Pack because it is a Gregtech Based Pack wich is only avaiable for MC 1.7.10.

**Comment by jaredlll08** [comment]
I know, and unfortunatly, the next thing I plan on doing for modtweaker is to update it to 1.8.9 :/ maybe I'll try get this in for the last 1.7 release, but really, no promises

**Comment by Dream-Master** [comment]
Ok. Thanks

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.

**Comment by Dream-Master** [comment]
This is one feature i realy need for my modpack but i guess i have to implement this via Java in my Core Mod.

**Comment by Voidi** [comment]
Da wirst do wohl rumprobieren müssen; Ich habe ein wenig mit den Functionen der API rumprobiert, aber die auch nicht wirklich dokumentiert ist bin ich da nicht weitergekommen. Außerdem wolle wir uns jetzt auf 1.9+ konzentrieren

**Comment by Dream-Master** [comment]
Ja gut mein Modpack ist für 1.7.10 und dafür wäre das super. Aber dann muss ich mal in den code schauen.
