### ISSUE TITLE
[Suggestion] Galacticraft Nasa Workbench integration

### ISSUE THREAD

**Issue by Dream-Master** [MineTweaker/ModTweaker#219]
I would appreciate it when you add support for the GalactiCraft Nasa Workbench.

**Comment by Dream-Master** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/recipe/INasaWorkbenchRecipe.java

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/recipe/RecipeManagerGC.java

**Comment by jaredlll08** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/GalacticraftRegistry.java just for later use.

**Comment by Tsyklop** [comment]
add support for all machines pls!

**Comment by Yulife** [comment]
Feel free to PR the support.

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.

**Comment by Tsyklop** [comment]
@Voidi why?

**Comment by Dream-Master** [comment]
It's very hard to implement. If you are using Avaritia 9x9 crafting table and disabled the Nasa workbench this would be much easier.

**Comment by Yulife** [comment]
@Tsyklop GC aint 1.10.2 yet :)
