### ISSUE TITLE
[Suggestion] Add support for Fuzzy Wildcard for Thermal Expansion

### ISSUE THREAD

**Issue by Tsyklop** [MineTweaker/ModTweaker#243]
Added to this Pulverizer recipe: Iron helmet -> iron ingots. But faced with such a problem that the helmet can be a bit used and the Pulverizer will not crush it. Get: id: Metadata = 306: 2, for example.

In the script, I did so: <minecraft: iron_helmet: *>. But nothing has changed.

**Comment by Voidi** [comment]
To match a item with all Metadata you have to use '*'.
For example: `<minecraft:iron_helmet:*>`

**Comment by Yulife** [comment]
You no longer use ID's in Minetweaker 1.7.10. Please use the unlocalized names by using /mt hand on the item if you are holding it.

**Comment by Tsyklop** [comment]
@Voidi I write this:
`Pulverizer.addRecipe(5000, <minecraft:iron_helmet>, <minecraft:iron_ingot> * 2, <ThermalFoundation:material>, 10);`

But if I try to put the damaged helmet put in the Pulverizer it does not rely ...

I tried to write this: `<minecraft:iron_helmet:*> ` But I still can not put a damaged helmet ..

@Yulife I wrote as needed, the example above ..

**Comment by Yulife** [comment]
It sounded like you used IDs in the in the script. Seems like wildcard support is not there for TE machines at the moment.

**Comment by Tsyklop** [comment]
@Yulife I turn to developers. Can do.

**Comment by Yulife** [comment]
No, the support for wildcard may be in TE just not in Modtweaker.

**Comment by Tsyklop** [comment]
@Yulife I got what you mean. I wrote developers TE

**Comment by jaredlll08** [comment]
No you did not. this has NOTHING at all to do with TE developers, we told you that.

**Comment by Tsyklop** [comment]
@jaredlll08 Oops. I just do not understand that this is your question.

**Comment by Yulife** [comment]
I told you it before. :neutral_face:

**Comment by Tsyklop** [comment]
@Yulife  Oh well. But what I need it's not working. If the item is damaged it does not lay down in the machine, only if the damage from the register. For example so: <minecraft: iron_helmet: 15>

**Comment by UndeadZeratul** [comment]
isn't there a method you can call to tell something to not care what damage/metadata value an item has?

http://minetweaker3.powerofbytes.com/wiki/Tutorial:Basic_Recipes#Subitems_and_damage_values

Like that, would that work?

**Comment by Tsyklop** [comment]
@UndeadZeratul I try, but dont work...

**Comment by jaredlll08** [comment]
Did you use the wildcard metadata?

**Comment by UndeadZeratul** [comment]
I think that was his first attempt, but I may be wrong.

**Comment by Tsyklop** [comment]
Look. What I mean https://youtu.be/jasclkH0dOE

**Comment by UndeadZeratul** [comment]
And that same thing happens when you try to do ```<minecraft:iron_helmet>.anyDamage()``` instead?

**Comment by Tsyklop** [comment]
@UndeadZeratul And so I have to indicate the error:
![2015-09-17_22 05 12](https://cloud.githubusercontent.com/assets/6783568/9943151/5813a75c-5d88-11e5-81f6-d1651720c482.png)

**Comment by Tsyklop** [comment]
There are news?

**Comment by jaredlll08** [comment]
That is user error, please look at your script.

**Comment by jaredlll08** [comment]
Did you look at the script yet?

**Comment by jaredlll08** [comment]
any news?

**Comment by jaredlll08** [comment]
How long?

**Comment by jaredlll08** [comment]
It is user error

**Comment by jaredlll08** [comment]
Fix script

**Comment by jaredlll08** [comment]
there no word on this

**Comment by jaredlll08** [comment]
Hello? why don't you reply?!

**Comment by jaredlll08** [comment]
I told you this is user error, please look at script and tell us more info

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.
