### ISSUE TITLE
[Suggestion] - Minefantasy2 Support

### ISSUE THREAD

**Issue by Slither88** [MineTweaker/ModTweaker#266]
Hi

Could you add Minefantasy 2 support?

Link to Mod:  http://minecraft.curseforge.com/projects/minefantasy2

**Comment by jaredlll08** [comment]
Is the mod open source?
Where am I meant to find out what the mod does?
Is this a full conversion mod? (Think TerraFirmaCraft)

**Comment by Slither88** [comment]
Not a full conversion. 
As far as I can tell the mod is not open source and there is not a wiki for it that has all the info about the mod, it has an in-game "guide" in the form of a research book though. I will try and find out.
MF2 is like the wuss mode TerraFirmaCraft. Same ideas just a bit easier, and differently implemented.

**Comment by Voidi** [comment]
https://github.com/jaredlll08/ModTweaker2/wiki/Requesting-Mod-Support

**Comment by Yulife** [comment]
If the mod ever gets back to 1.10, please reopen.
