### ISSUE TITLE
[Suggestion]Advanced rocketry support

### ISSUE THREAD

**Issue by wormzjl** [MineTweaker/ModTweaker#271]
Mod can be found here
http://minecraft.curseforge.com/projects/advanced-rocketry

And source here
https://github.com/zmaster587/AdvancedRocketry

**Comment by Voidi** [comment]
https://github.com/jaredlll08/ModTweaker2/wiki/Requesting-Mod-Support

**Comment by Yulife** [comment]
If the mod ever gets back to 1.10, please reopen.

**Comment by tjsd** [comment]
time to reopen? :)

**Comment by wormzjl** [comment]
ar got it's own recipe customization system already
