### ISSUE TITLE
Thermal Expansion Phytogenic Insolator Recipe Bug

### ISSUE THREAD

**Issue by HaruDasom** [MineTweaker/ModTweaker#278]
Mods
MineTweaker3-1.7.10-3.0.9C
ModTweaker2-0.9.4

Code : http://pastebin.com/AG550Ayv
Minetweaker log : http://pastebin.com/bgJHRmyP

How to reproduce :
1. Run minecraft and Enter a world. All recipes work fine at this moment.
2. Leave the world.
3. Enter a world. (the same world, or the other worlds)
4. Recipes do not work.

I tested it only in the single player.

**Comment by Voidi** [comment]
Can't reproduce this. What's mod_ecru_MapleTree for a mod?
Could you provide the forge log (fml-client-latest.log)?

**Comment by HaruDasom** [comment]
Here is the forge log :
https://drive.google.com/open?id=0B8AasfSHs7G5cjN2SHVlOU9pbzg

mod_ecru_MapleTree is MapleTree mod. It is a Japanese mod, so may be not known well.
http://forum.minecraftuser.jp/viewtopic.php?t=6984

**Comment by Voidi** [comment]
Ok I able to reproduce that. But could you please make some test to narrow down which mod / item / zenscript command causes the problem. I don't want to test through all the mods mentioned in your script file.

**Comment by jaredlll08** [comment]
fairly simple problem here... look on line 133 of the provided error, it needs hashcode to be the same, and equals to be the same, however, we only have equals being the same, so that needs to be changed, either add hashcode, or remove equals

**Comment by HaruDasom** [comment]
I tested on several codes with several modes then it seems that both MapleTree mod and AppleMilkTea mod are problems. Either of them does not cause the problem. But when I put them together in the mods folder, the problem occurs.

[Forge Version]
1.7.10-1448

[MODS List]
OptiFine_1.7.10_HD_U_B7

CodeChickenCore-1.7.10-1.0.6.43
NotEnoughItems-1.7.10-1.0.4.106

CoFHCore-[1.7.10]3.0.3-303
ThermalFoundation-[1.7.10]1.2.0-102
ThermalExpansion-[1.7.10]4.0.3B1-218

MineTweaker3-1.7.10-3.0.9C
ModTweaker2-0.9.4

MapleTree Forge v1.1.32c

AppleMilkTea2-1.7.10_2.8o
PotionExtension-1.7.10-1.1.0 (Coremod for AppleMilkTea)
http://defeatedcrow.wiki.fc2.com/wiki/AppleMilkTea!ver2%28English%29



And it seems that using phytogenic insolator codes with the crops from MapleTree or AppleMilkTea cause this bug. I tested on the tomato from MapleTree and the mint from AppleMilkTea.

Code : http://pastebin.com/d90xT6wV
Minetweaker Log : http://pastebin.com/FkjnWPVu

I also wrote a code with brown mushroom(vanilla crop). Then it doesn't cause the bug (All recipes are work), but I got a similar log.

Code : http://pastebin.com/WWUC3de0
Minetweaker Log : http://pastebin.com/kYchCAVi
