### ISSUE TITLE
Crucible Recipes appearing incorrectly in Thaumonomicon if output item can be produced in Macerator

### ISSUE THREAD

**Issue by Xavion3** [MineTweaker/ModTweaker#296]
So far I've only seen this occur with gregtech items set as the output of a crucible recipe when adding the recipe to the thaumonomicon, the really weird part is that the recipes chosen seem to have their inputs taken from either the macerator or pulverizer recipes. Note the recipes still work correctly, they just render incorrectly in the thaumonomicon and seem to have issues with the thaumcraft NEI plugin.

For an example, adding a method to produce naquadah dust in the crucible leads to the following three recipes, all of which seem to have a consistent amount of perditio, however I have no idea where it's getting the amount from. All of these recipes have as the input an item you can put in the macerator, and the output as the item I told it to add a page for, with the correct amount as if you put the shown input item into a macerator.

<img width="305" alt="screen shot 2016-01-10 at 7 12 56 pm" src="https://cloud.githubusercontent.com/assets/3487253/12220803/f53b9da4-b7d4-11e5-839e-9b83dae12f53.png">
<img width="315" alt="screen shot 2016-01-10 at 7 52 49 pm" src="https://cloud.githubusercontent.com/assets/3487253/12220804/f540a54c-b7d4-11e5-979f-bcbd7c11019a.png">
<img width="305" alt="screen shot 2016-01-10 at 7 53 28 pm" src="https://cloud.githubusercontent.com/assets/3487253/12220805/f5448860-b7d4-11e5-83ec-26c38dbe8c59.png">

I'm also including an example of what happens when I use an output item that isn't an output of the macerator, which causes it to appear correctly.
<img width="298" alt="screen shot 2016-01-10 at 8 08 30 pm" src="https://cloud.githubusercontent.com/assets/3487253/12220823/0b91eb34-b7d6-11e5-89d7-010b85fa573e.png">

**Comment by jaredlll08** [comment]
We need your scripts please

**Comment by Xavion3** [comment]
mods.thaumcraft.Crucible.addRecipe("NODES", <gregtech:gt.metaitem.01:2324>, <Thaumcraft:ItemResource:17>, "auram 1");
    mods.thaumcraft.Research.addCruciblePage("NODES", <gregtech:gt.metaitem.01:2324>);
    mods.thaumcraft.Research.refreshResearchRecipe("NODES"); 

That script will produce the error, tested with modtweaker 0.9.5, gregtech 5.09.19, and thaumcraft 4.2.3.5 in an instance containing no mods but those and the required mods for them. It'll add the crucible page to the aura and nodes research in the basics tab, it should display as a void seed to a naquadah dust for 1 auram, what actually displayed for me was a naquadah hoe head to 2 naquadah dust for 4 perditio, and it does display it consistently on restarting the game.

**Comment by Voidi** [comment]
Closed due MC1.7.10 end of life.
