### ISSUE TITLE
[Request] Better Beginnings support

### ISSUE THREAD

**Issue by RebirthGaming** [MineTweaker/ModTweaker#305]
1.7.10 development for this mod has halted in favor for 1.8. However, the developer of BB has stated that anyone willing to add MT support can submit a PR and it'll be merged.  

Mod adds early game progression with new methods of smelting and crafting stuff. 

This request is for MT support to be added to BB (1.7.10 version)

BB Github: https://github.com/einsteinsci/betterbeginnings

Post stating any willing contributor to submit a PR for MT support:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2192122-betterbeginnings-mod-9000-downloads?page=26

**Comment by Yulife** [comment]
Well why should it be merged into Modtweaker and not in the mod itself?

**Comment by jaredlll08** [comment]
I think this guy is asking us to add support for BB, IN BB. like I go fork their repo, add it and make a PR...

**Comment by Yulife** [comment]
This mod is updated to 1.10 I think.

**Comment by Leviathan143** [comment]
@Yulife 
BB is not on 1.10, we're still on 1.8.0. I really need to talk to einsteinsci about updating.

**Comment by Yulife** [comment]
Ok
