### ISSUE TITLE
[help?] Thermal expansion pulverizer recipies.

### ISSUE THREAD

**Issue by WarrenElite** [MineTweaker/ModTweaker#306]
I have been trying to get osmium gravel (<exnihilo:osmium_gravel>) to go into the pulverizer and come out as 2 osmium dust (<Mekanism:Dust:2> * 2) however when i use this line:
mods.thermalexpansion.Pulverizer.addRecipe(3200, <exnihilo:osmium_gravel>, <Mekanism:Dust:2> * 2);
nothing happens. can someone explain what i have done wrong please?

**Comment by Tsyklop** [comment]
forgot symbol "<" and ">"

mods.thermalexpansion.Pulverizer.addRecipe(3200, <exnihilo:osmium_gravel>, <Mekanism:Dust:2 * 2>);

**Comment by Yulife** [comment]
That's Github's markdown automatically removing "bigger than" and "lower than" symbols.
