### ISSUE TITLE
[1.8] [Thaumcraft 5] Shapeless Arcane Recipes are wonky

### ISSUE THREAD

**Issue by Yulife** [MineTweaker/ModTweaker#309]
If you add a Shapeless Arcane recipe with Modtweaker things get slightly weird.

**Issue 1:**
Somehow one item acts as a .reuse and isn't being used when the crafting is done. The items used also go directly into the inventory, sort of if you use a bucket in a recipe and it goes directly down into your inventory.

**Issue 2:**
The recipe does not use the ingredients (except on the first click). You can keep on clicking on the item output even if the ingredients are marked with a null in the grid. [Example](https://www.dropbox.com/s/s3tsla3mgwmmip3/2016-02-27_19-31-31.mp4?dl=0)

**Issue 3:**
Shift-left-clicking the output item to craft all the items in the grid in one click it crashes to Desktop. Jared you have the log :P

**Comment by jaredlll08** [comment]
Log for reference, once again, it can't be us...
http://paste.ee/p/GeIXK
