### ISSUE TITLE
[1.8.9] Thaumcraft 5 - Crucible Recipes

### ISSUE THREAD

**Issue by ReTeYeZ** [MineTweaker/ModTweaker#310]
I'm currently unable to add any Crucible recipes because of following error:
`
ERROR: Thaumcraft.zs:4 > a method available but none matches the parameters (string, minetweaker.item.IItemStack, minetweaker.item.IItemStack, string)
`
I tried it with the example script from the wiki
`
mods.thaumcraft.Crucible.addRecipe("ENTROPICPROCESSING", <minecraft:dirt>, <minecraft:sapling>, "terra 2, perditio 4");
`
and changed a little bit here and there in the hope to figure it out myself, no luck so far. Though the values that are passed seem correct to me.

**Comment by Yulife** [comment]
The wiki isn't Thaumcraft 5 but 4. I'll try to do TC5 doc soon. For now check the parameters in the code.

**Comment by jaredlll08** [comment]
Use the params at
www.blamejared.com/new/modtweaker/1.8.9/

**Comment by ReTeYeZ** [comment]
I can't seem to figure it out. I did it like in the doc by jaredlll08 (thx) but it doesn't want to work:
`mods.thaumcraft.Crucible.addRecipe("ENTROPICPROCESSING", <minecraft:stick>, <minecraft:grass>, "terra 1");` Same error.

I also took a look at the addRecipe() method in the Crucible Handler, it expects the same parameters
as shown in the doc: `String key[], IItemStack result, IIngredient catalyst, String aspects`

What's about that "IIngredient"? Since the example by jared passes an IItemStack instead (<minecraft:grass>).

**Comment by jaredlll08** [comment]
IIngredient can be an IItemStack

**Comment by jaredlll08** [comment]
Can this be closed?

**Comment by hron84** [comment]
@jaredlll08 no, crucible recipes aren't work. I tried so many ways to make them, but none of them work.

I tried the following recipe: `Crucible.addRecipe("ENTROPICPROCESSING", <minecraft:gunpowder> * 5, <minecraft:tnt>, "perditio 4");`

**Comment by jaredlll08** [comment]
What error did you get?

**Comment by hron84** [comment]
@jaredlll08 same as the original poster.

**Comment by jaredlll08** [comment]
Really? then look at what I replied to the original poster.because thaumcraft 5 support is new, the wiki has not been updated, visit: www.blamejared.com/new/modtweaker/1.8.9/ for more info on the problem.

**Comment by hron84** [comment]
@jaredlll08 sorry, but what is key[] ? An array of what? There is no examples on that page and I have no clue what type of array I need.

**Comment by jaredlll08** [comment]
I don't know, there is no documentation for the TC api, so I can't tell you, I suggest just make the string[] and put 1 string in it

**Comment by jaredlll08** [comment]
Also right now the page is updating, so things may not appear.

**Comment by hron84** [comment]
@jaredlll08 also the `Research.addPage` is not correct, I use this: `Research.addPage("PEARLSHARD", "pearlshard.research_page.one");` but ModTweaker complains about INFUSION_ENCHANTMENT (with no other information). So there is so many broken things.

**Comment by jaredlll08** [comment]
That is because you are using a newer thaumcraft than we support. I think I should just stop 1.8 dev, 1.9 is just around the corner, hopefully we will have more mods on it.

**Comment by hron84** [comment]
@jaredlll08 but before you stop 1.8 dev, can you upgrade the TC dependency? So many ppl uses the 1.8.9 TC currently (in FTB Unstable, Pioneers, and many other modpacks) and MT support would be really appreciated).

Currently the researches without pages crashes the client.
