### ISSUE TITLE
[1.8.9] Error executing thaumcraft.zs: INFUSION_ENCHANTMENT

### ISSUE THREAD

**Issue by Serifina** [MineTweaker/ModTweaker#311]
I'm trying to add research via ModTweaker and I keep getting an error about infusion enchantment - even though I'm not touching it at all. If I load Minecraft fresh, the BASICS tab is empty. At this point, I have no clue what I'm doing wrong or if something is broken. So here is my [script](http://pastebin.com/7Y2LhaYZ), and here is my [MineTweaker.log](http://pastebin.com/3GG9bQRA).

**Comment by jaredlll08** [comment]
Can we get the game log please?

Also take a look here: "skymagic.research_page.CRIMRITES", I think that is localizing something to what is crashing

**Comment by Serifina** [comment]
Game log [here](https://gist.github.com/Serifina/e9fe1074da8d6a868b0c).

As to that localization, it's the localization for the research page added the line directly above it. Those three lines as a block are adding a research, adding a page to the research, and adding the localization for the research so it actually says something. Did I screw up something there?

**Comment by jaredlll08** [comment]
The file you uploaded seems to be incomplete

**Comment by jaredlll08** [comment]
It seems that you are using a newer version of TC than we support, or an older version, I honestly can't tell without knowing what version it is.

**Comment by Serifina** [comment]
I'm using the most recent Thaimcraft - 1.8.9-5.2.1.

**Comment by jaredlll08** [comment]
Ok yea, I built it off 5.1.6, so either downgrade or wait for me to update it

**Comment by Serifina** [comment]
That'd do it.

Also, same script, it throws an error if I try to put a reuse() command on an infusion recipe ingredient. Is that also due to it not being up to date or is there a better way to handle that?
